version: 2
jobs:
  build:
    docker:
      image: circleci/python:3.7.0-stretch-node-browsers
    steps:
      - run:
        name: Node Version
        command: node -v 
      - run:
          name: Install node-red 
          command: sudo npm install -g --unsafe-perm node-red
      -run: 
        name: Clone Repo
        command: git clone https://github.com/ARMmbed/node-red-contrib-mbed-cloud.git
      - run:
          name: Install dependencies 
          command: npm install