version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout 
      - run:
          name: Install npm dependencies 
          command: npm install
      - run: 
          name: Build nodes
          command: npm run gulp 